os: osx
language: node_js
node_js: node
env:
  - PATH=/Applications/Sketch.app/Contents/Resources/sketchtool/bin:$PATH
before_install:
  - brew cask install sketch
  - sketchtool -v
script:
  - npm run build
deploy:
  # Warning: gh-pages branch must exist on Github repository
  # See https://github.com/travis-ci/travis-ci/issues/9662
  provider: pages
  local-dir: dist
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
cache:
  directories:
    - $HOME/.npm
    - $HOME/Library/Caches/Homebrew
